spring:
  datasource:
    url: jdbc:h2:file:/DATA/daniil4jk/randomChatBot/userDataBase;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate: